import re
import sys
import json
import difflib
from pathlib import Path

EXCLUDE_PATTERNS = (
    "cockpit", "costview", "dispatch", "decision", "crx", "boxing", "blackjack", 
    "cards", "cardtable", "market", "store", "economy", "customization", 
    "picker", "npc", "animals", "death", "edit.mode",
    "designs.panel", "agent.manager", "briefing", "bouts", "elevator", 
    "marriage", "smoking", "excursion", "commute", "weather", "nux", 
    "settings.panel", "talk", "naughty"
)

def parse_script_tags(html_content):
    """Extract script src basenames from HTML content."""
    return [Path(match).name for match in 
            re.findall(r'<script[^>]+src="([^"]+)"', html_content)]

def categorize_scripts(scripts):
    """Sort scripts into keep/exclude lists based on patterns."""
    keep = []
    exclude = []
    
    for script in scripts:
        if any(pattern in script for pattern in EXCLUDE_PATTERNS):
            exclude.append(script)
        else:
            keep.append(script)
    
    exclude.sort()
    return keep, exclude

def generate_manifest(html_path):
    """Generate manifest JSON from HTML file."""
    html_content = Path(html_path).read_text()
    scripts = parse_script_tags(html_content)
    keep, exclude = categorize_scripts(scripts)
    
    return {
        "_comment": f"Generated by {Path(__file__).name}",
        "keep_scripts": keep,
        "excluded_scripts": exclude
    }

def write_manifest(manifest, output_path):
    """Write manifest to file with deterministic JSON formatting."""
    with open(output_path, 'w') as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write('\n')

def check_manifest(html_path, manifest_path):
    """Check if existing manifest matches regenerated one."""
    if not manifest_path.exists():
        print("missing", file=sys.stderr)
        return 1
    
    current = manifest_path.read_text()
    new_manifest = generate_manifest(html_path)
    new_json = json.dumps(new_manifest, indent=2, sort_keys=True) + '\n'
    
    if current == new_json:
        print("SHAREDFLOOR-MANIFEST OK")
        return 0
    
    # Show unified diff on mismatch
    diff = difflib.unified_diff(
        current.splitlines(),
        new_json.splitlines(),
        fromfile=str(manifest_path),
        tofile='regenerated'
    )
    print('\n'.join(diff), file=sys.stderr)
    return 1

def main():
    html_path = Path(__file__).parent.parent / 'static' / 'index.html'
    manifest_path = Path(__file__).parent.parent / 'sharedfloor_manifest.json'
    
    if '--check' in sys.argv:
        sys.exit(check_manifest(html_path, manifest_path))
    else:
        manifest = generate_manifest(html_path)
        write_manifest(manifest, manifest_path)

if __name__ == '__main__':
    main()
